### PR TITLE
fix divide by zero when the graph is empty

### PR DESCRIPTION
**Pull request by oflatt**

### CODE REVIEW

**Comment by oflatt** [comment]
Did the build error because I don't have the required docker credentials?

**Comment by cjmyers** [comment]
@michael13162 can you add Oliver to the repo and help him with docker credentials.

**Comment by michael13162** [comment]
Added Oliver to the repo.

The docker username and password are set I believe.  Looks like the docker build/push script is hanging on asking for a username because the credential values from the settings aren't being exported?  @zachzundel

**Comment by zachzundel** [comment]
Yes, Oliver's PR is not given the credentials because they are protected. If not, he could submit a PR that exposed the credentials. We fixed this for SynBioHub by only running the push step on commits to master. @michael13162 : you should be able to figure out the changes necessary by looking at .travis.yml in SynBioHub

**Comment by michael13162** [comment]
I tried emulating what you have you SynBioHub, but it's still running the push when I retry the build.
https://github.com/michael13162/SBOLExplorer/blob/master/.travis.yml

**Comment by zachzundel** [comment]
Could the build not be incorporating the commit with your Travis changes since this is a branch and that's master? @oflatt rebasing off of the new tip of master could maybe help

**Comment by zachzundel** [comment]
Also, it looks like your changes won't even build on new changes. Really, they should build on _all_ commits/PRs, and only _push_ on master

**Comment by oflatt** [comment]
for now, I created another pull request #41

**Pull request closed without merging**
