### PR TITLE
Better error handling

### PR DESCRIPTION
**Pull request by zachzundel**
Improves error handling by wrapping all requests in try/catch and recovering where possible.

### CODE REVIEW

**Comment by zachzundel** [comment]
Please take a look @michael13162.

@cjmyers this should eliminate failures when either SynBioHub or Web of Registries fails.

**Comment by michael13162** [comment]
LGTM

**Comment by cjmyers** [comment]
@michael13162 Can you merge it into your code base then?

**Comment by michael13162** [comment]
Also added Zach as a collaborator for this repo.

**Pull request merged**
